#https://mmistakes.github.io/minimal-mistakes/docs/configuration/
#https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
locale: en-GB
title: OSBO Tech Blog
description: Blogging about tech in OSBO
email: blog@onestopbeauty.online
#url: https://blog.onestopbeauty.online
#logo: "/assets/images/osboLogo.png"

twitter_username: lili_z
github_username: lilianaziolek
repository: lilianaziolek/lilianaziolek.github.io
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
search: false


# Build settings
markdown: CommonMarkGhPages
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Liliana Ziolek"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Years and years of Java development. Now building One Stop Beauty Online. Still loads of Java, plus other new toys."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.onestopbeauty.online"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lili_z"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lilianaziolek"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/justosbo"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/justosbo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lilianaziolek"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/justosbo"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider               : "disqus"
  disqus:
    shortname            : "osbo-tech-blog"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-52555041-2